<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="SimpleTest" skipped="0" failures="1" errors="0" tests="2" assertions="3" time="7.887800029493519e-05">
  <testcase name="test_FOO_EXCEPTION" classname="SimpleTest" assertions="1" time="5.583600022873725e-05">
    <failure type="test_FOO_EXCEPTION" message="RuntimeError expected but nothing was raised.">
Failure:
test_FOO_EXCEPTION(SimpleTest) [./unit-template.rb:17]:
RuntimeError expected but nothing was raised.
    </failure>
  </testcase>
  <testcase name="test_MSG_EXCEPTION" classname="SimpleTest" assertions="2" time="2.3042000066197943e-05">
  </testcase>
</testsuite>
